# Corite

browser:
    CHROME_HEADLESS
#browser: FIREFOX_HEADLESS

dimension:
    width: 375
    hight: 667

csss:
    confirmlinks:
       registration: "a.confirm-registration"
       moderation: "a.inform-campaign-to-moderate"
       accepted: "a.inform-creator-about-accept"
    loginpage:
       email: "[name=email]"
       password: "[name=password]"
       submit: "form .mat-flat-button.mat-primary"
    registerpage:
       yourEmailIn: "input[name=email]"
       firstNameIn: "input[name=fname]"
       lastNameIn: "input[name=lname]"
       passwordNewIn: "input[name=new-password]"
       passwordConfirmIn: "input[name=new-password-confirm]"
       telephoneIn: "input[name=phone]"
       registerSubmit: "button.mat-flat-button"
       registerConfirmationTxt: "page-account-register > main > account-register > div > p > strong" # email of a jast registered user 
    thankyoupage:
       txtContent: "app-root"
    explorepage:
       loginBtn: "a[routerlink='/user/login']"
       userName: "a[routerlink='/profile']"
       profileBtn: ".button.mat-icon-button"
       menuAdmin: "a.mat-list-link[href='https://admin.dev.corite.com/']"
       menuMyCampaign: "a.mat-list-link[href='/my-campaigns']"
       menuLogoutBtn: "button.mat-list-link"
       startCampaignTab: "a.mat-tab-link:nth-child(2)"
       firstCampaignInList: "campaign-explore-teaser"
    explorecappaignpage:
       buyCoritesBtn: "a[routerlink=invest]"
    startcampaignpage:
       campaignImage: "campaign-group-own-image input"
       campaignSong: "campaign-group-own-song input"
       campaignName: "campaign-group-own-basics input[name='campaign[name]']"
       campaignArtist: "campaign-group-own-basics input[name='campaign[artist]']"
       campaignGenre: "campaign-group-own-genre input"
       campaignGenreSelect: "div.mat-autocomplete-panel > mat-option:nth-of-type(1)"
       campaignValue: "mat-slider"
       textArea: "textarea"
       iagree: ".mat-checkbox-inner-container"
       campaignPublish: ".mat-flat-button.mat-primary"
    moderationpage:   
       acceptedModeration: "#campaign_moderationStatus_2"
       saveChangesModeration: "button.action-save"
    investpage:
       campaignStatus: "campaign-status"
       slider: "mat-slider"
       nextBtn: ".mat-flat-button.mat-primary"
       buyCoritesBtn: "a[routerlink=invest]"
       accentBtn: ".mat-flat-button.mat-accent"
       pledgeBtn: ".mat-flat-button.mat-primary"
    adminpage:
       searchQuery: "input[name=query]" 
       searchBtn: "button[type=submit].btn"
       dropdownMenuBtn: "td div button.btn.dropdown-toggle"
       deleteUserBtn: "a.action-delete"
       confirmDeleteUserBtn: "#modal-delete-button"
       searshResultsNumber: "h1.title > strong"
       detectedItem: "tr[data-id]"

flowsss:
    loginlogout:

    registerwithemail:
        
    startcampaign:
#0
      - csss: "campaign-explore-teaser" # css selector to check hash of its innerhtml
        hash: "1327027928" # hashcode of the element's innerHTML
    
patterns:
#  id: pattern
     1: The day before you came

logger:
    debug: true
    action: true
    info: true
    passed: true
    warning: true
    failed: true

runtests: 
   - loginlogout
   - registerwithemail
   - startcampaign