# Corite

browsers:
    IPhone6:
        type: CHROME_HEADLESS
        file: "/Users/andrew/bin/chromedriver"
        width: 375
        hight: 667
    DescTop:
        type: CHROME_HEADLESS
        file: "/Users/andrew/bin/chromedriver"
        width: 1600
        hight: 800

csss:
    confirmlinks:
       registration: "a.confirm-registration"
       moderation: "a.inform-campaign-to-moderate"
       accepted: "a.inform-creator-about-accept"
       declined: "a[data-e2e=informCreatorAboutDecline]"
       informCreatorAboutFunded: "a[data-e2e=informCreatorAboutFunded]"
       informBackerAboutFunded: "a[data-e2e=informBackerAboutFunded]"
    commonelements:
       matError: "mat-error"
       submitBtn: "form .mat-flat-button.mat-primary"
       accentBtn: "form .mat-flat-button.mat-accent"
    loginpage:
       email: "[name=email]"
       password: "[name=password]"
       
       googleBtn: "button.google.mat-flat-button.mat-primary"
       googleEmailIn: "input[name=identifier]"
       googlePasswordIn: "input[name=password]"
       googleIdentifierNextBtn: "#identifierNext"
       googlePasswordNextBtn: "#passwordNext"
       
       facebookBtn: "button.facebook.mat-flat-button.mat-primary"
       facebookEmailIn: "#email"
       facebookPasswordIn: "#pass"
       facebookLoginBtn: "#loginbutton"
       
    registerpage:
       yourEmailIn: "input[name=email]"
       firstNameIn: "input[name=fname]"
       lastNameIn: "input[name=lname]"
       passwordNewIn: "input[name=new-password]"
       passwordConfirmIn: "input[name=new-password-confirm]"
       telephoneIn: "input[name=phone]"
       registerConfirmationTxt: "page-account-register > main > account-register > div > p > strong" # email of a jast registered user
    thankyoupage:
       txtContent: "app-root"
    explorepage:
       loginBtn: "a[routerlink='/user/login']"
       userNameTxt: "a[routerlink='/profile']"
       profileBtn: ".button.mat-icon-button"
       menuAdministration: "a[data-e2e='administration']"
       menuMyCampaigns: "a[data-e2e='my-campaigns']"
       menuPortfolio: "a[data-e2e='portfolio']"
       menuProfile: "a[data-e2e='profile']"
       menuPayouts: "a[data-e2e='payouts']"
       menuLogoutBtn: "button[data-e2e='logout']"
       startCampaignTab: "a[data-e2e=tab-start-campaign]"
       exploreTab: "a[data-e2e=tab-explore]"
       teaser: "explore-teaser[data-e2e=campaign-{id}]"
       teaserCampaign: "explore-teaser[data-e2e=campaign-{id}] .title>a"
    portfoliopage:
       releasedCampaignName: "h2.title"
       releasedMyCorites: "article div.value > app-corites > div"
    startcampaignpage:
       campaignImage: "campaign-group-own-image input"
       campaignSong: "campaign-group-own-song input"
       campaignName: "campaign-group-own-basics input[name='campaign[name]']"
       campaignArtist: "campaign-group-own-basics input[name='campaign[artist]']"
       campaignGenre: "campaign-group-own-genre input"
       campaignGenreSelect: "div.mat-autocomplete-panel > mat-option:nth-of-type(1)"
       campaignValue: "mat-slider"
       textArea: "textarea"
       iagree: ".mat-checkbox-inner-container"
    moderationpage:   
       acceptedModeration: "#campaign_moderationStatus_2"
       saveChangesModeration: "button.action-save"
       campaignModerationComment: "#campaign_moderationComment"
    investpage:
       campaignStatus: "campaign-status"
       slider: "mat-slider"
       anotherCardBtn: "span.change"
       newCardBtn: ".is-empty>div"
       thankyou: "campaign-invest-thanks"
       buyCoritesBtn: "button.mat-flat-button.mat-primary"
    adminpage:
       searchQuery: "input[name=query]" 
       searchBtn: "button[type=submit].btn"
       dropdownMenuBtn: "td div button.btn.dropdown-toggle"
       deleteItemBtn: "a.action-delete"
       confirmDeleteItemBtn: "#modal-delete-button"
       searchResults: "h1.title"
       detectedItem: "tr[data-id]"
       allCampaignsMnu: "a[data-e2e='menu.campaign.all']"
       allOrdersMnu: "a[data-e2e='menu.order.all']"
       allUsersMnu: "a[data-e2e='menu.user.all']"
    releaseinfopage:
       songName: "input[name='campaign[release][songName]']"
       cover: "app-file-upload div.item input"
       label: "input[name='campaign[release][label]']"
       company: "input[name='campaign[release][company]']"
       isrc: "input[name='campaign[release][ISRC]']"
       artists: "input[name='campaign[release][contribArtists]']"       
       producers: "input[name='campaign[release][contribProducers]']"
       composers: "input[name='campaign[release][contribComposers]']"
       mixers: "input[name='campaign[release][contribMixers]']"
       publishers: "input[name='campaign[release][contribPublishers]']"
       countries: "div.mat-select-value"
       country: "#mat-option-83"
       date: "input[min]"
    
patterns:
#  id: pattern
     1: Temporary19235 Release-Campaign
     2: Temporary19235 Start-Campaign
     3: 355 #Campaign id for testing payment with incorrect cards. The campaign will be failed each 30 days. So we need to create new one manually. 

logger:
    debug: true
    action: true
    info: true
    passed: true
    warning: true
    failed: true

runtests:
   - loginlogout
#   - registerwithemail
#   - startcampaign
#   - releaseinformation
#   - releasecampaign
#   - incorrectcard
#   - payouts