browser:
    CHROME_HEADLESS
#browser: FIREFOX_HEADLESS

dimension:
    width: 375
    hight: 667

csss:
    confirmlinks:
       registration: "a.confirm-registration"
       moderation: "a.inform-campaign-to-moderate"
       accepted: "a.inform-creator-about-accept"
    loginpage:
       email: "[name=email]"
       password: "[name=password]"
       submit: "form .mat-flat-button.mat-primary"
    registerpage:
       yourEmailIn: "input[name=email]"
       firstNameIn: "input[name=fname]"
       lastNameIn: "input[name=lname]"
       passwordNewIn: "input[name=new-password]"
       passwordConfirmIn: "input[name=new-password-confirm]"
       telephoneIn: "input[name=phone]"
       registerSubmit: "button.mat-flat-button"
       registerConfirmationTxt: "page-account-register > main > account-register > div > p > strong" # email of a jast registered user 
    thankyoupage:
       txtContent: "app-root"
    explorepage:
       loginBtn: "a[routerlink='/user/login']"
       userName: "a[routerlink='/profile']"
       profileBtn: ".button.mat-icon-button"
       menuAdmin: "a.mat-list-link[href='https://admin.dev.corite.com/']"
       menuMyCampaign: "a.mat-list-link[href='/my-campaigns']"
       menuLogoutBtn: "button.mat-list-link"
       startCampaignTab: "a.mat-tab-link:nth-child(2)"
       firstCampaignInList: "campaign-explore-teaser"
    startcampaignpage:
       campaignImage: "campaign-group-own-image input"
       campaignSong: "campaign-group-own-song input"
       campaignName: "campaign-group-own-basics input[name='campaign[name]']"
       campaignArtist: "campaign-group-own-basics input[name='campaign[artist]']"
       campaignGenre: "campaign-group-own-genre input"
       campaignGenreSelect: "div.mat-autocomplete-panel > mat-option:nth-of-type(1)"
       campaignValue: "mat-slider"
       textArea: "textarea"
       iagree: ".mat-checkbox-inner-container"
       campaignPublish: ".mat-flat-button.mat-primary"
    moderationpage:   
       acceptedModeration: "#campaign_moderationStatus_2"
       saveChangesModeration: "button.action-save"     
    adminpage:
        searchQuery: "input[name=query]" 
        searchBtn: "button[type=submit].btn"
        dropdownMenuBtn: "td div button.btn.dropdown-toggle"
        deleteUserBtn: "a.action-delete"
        confirmDeleteUserBtn: "#modal-delete-button"
       

flowsss:
    loginlogout:
#0
      - csss: "nav.top" # css selector to check html state before running a command
        hash: "2013493558" # hashcode of the element's innerHTML
#1
      - csss: "page-account-login"
        hash: "1370709605"
#2
      - csss: "page-account-login"
        hash: "1827752133"
#3
      - csss: "page-account-login"
        hash: "1649834707"
#4
      - csss: "page-account-login"
        hash: "1073467074"
#5
      - csss: "nav.top" # user is logined
        hash: "-1639161134"
#6
      - csss: ".mat-menu-panel" # logout begins — dropdown menu
        hash: "1971531868"

    registerwithemail:
#0
      - csss: "page-account-register" # css selector to check html state before running a command
        hash: "-476918324" # hashcode of the element's innerHTML
#1
      - csss: "nav.top" # login admin to delete just registered user
        hash: "2013493558"
#2
      - csss: "page-account-login"
        hash: "1370709605"
#3
      - csss: "page-account-login"
        hash: "1827752133"
#4
      - csss: "page-account-login"
        hash: "-1647707845"
#5
      - csss: "page-account-login"
        hash: "-371539158"
#6
      - csss: "nav.top" # login admin is completed
        hash: "1937758725"
#7
      - csss: "td.no-results"
        hash: "-1435612481"
        
    startcampaign:
#0
      - csss: "nav.top" # css selector to check html state before running a command
        hash: "2013493558" # hashcode of the element's innerHTML
#1
      - csss: "page-account-login"
        hash: "1370709605"
#2
      - csss: "page-account-login"
        hash: "1827752133"
#3
      - csss: "page-account-login"
        hash: "85652125"
#4
      - csss: "page-account-login"
        hash: "-1173293044"
#5
      - csss: "app-navigation" # user is logined
        hash: "-2040103819"
#6
      - csss: "nav.top" # css selector to check html state before running a command
        hash: "2013493558" # hashcode of the element's innerHTML
#7
      - csss: "page-account-login"
        hash: "1370709605"
#8
      - csss: "page-account-login"
        hash: "1827752133"
#9
      - csss: "page-account-login"
        hash: "1649834707"
#10
      - csss: "page-account-login"
        hash: "1073467074"
#11
      - csss: "app-navigation" # user is logined
        hash: "-1639161134"
#12
      - csss: "app-navigation" # user is logined
        hash: "-1278885044"
#13
      - csss: "app-navigation" # start campaing / press Start Campaing button
        hash: "-1639161134"
#14
      - csss: ""
        hash: "-1221524271"
#15
      - csss: ".mat-menu-panel"
        hash: "2013493558"
#16
      - csss: "page-campaign-own-list" # click My campaigns / check creating a campaign
        hash: "1370709605"      
#17
      - csss: ".mat-menu-panel" # logout user begins — dropdown menu
        hash: "1827752133"
#18
      - csss: "nav.top" # login admin to delete just creating campaign
        hash: "-1647707845"
#19
      - csss: "app-root"
        hash: "-371539158"
#10
      - csss: "app-root"
        hash: "1937758725"
#21
      - csss: "app-root"
        hash: "241679551"
    
patterns:
#  id: pattern
    1: Login | Corite
    2: Explore | Corite
    3: "mat-tab-link mat-tab-label-active" # It's classname of the tab Start Campaign if it's active 
    4: Sign Up | Corite
    5: All campaigns

logger:
    debug: true
    action: true
    info: true
    passed: true
    warning: true
    failed: true

runtests: 
   - loginlogout
   - registerwithemail
   - startcampaign