# Corite

browser:
    CHROME_HEADLESS
#browser: FIREFOX_HEADLESS

dimension:
    width: 375
    hight: 667

csss:
    confirmlinks:
       registration: "a.confirm-registration"
       moderation: "a.inform-campaign-to-moderate"
       accepted: "a.inform-creator-about-accept"
       declined: "a[data-e2e=informCreatorAboutDecline]"
       informCreatorAboutFunded: "a[data-e2e=informCreatorAboutFunded]"
       informBackerAboutFunded: "a[data-e2e=informBackerAboutFunded]"
    commonelements:
       matError: "mat-error"
       submitBtn: "form .mat-flat-button.mat-primary"
       accentBtn: "form .mat-flat-button.mat-accent"
    loginpage:
       email: "[name=email]"
       password: "[name=password]"
       
       googleBtn: "button.google.mat-flat-button.mat-primary"
       googleEmailIn: "input[name=identifier]"
       googlePasswordIn: "input[name=password]"
       googleIdentifierNextBtn: "#identifierNext"
       googlePasswordNextBtn: "#passwordNext"
       
       facebookBtn: "button.facebook.mat-flat-button.mat-primary"
       facebookEmailIn: "#email"
       facebookPasswordIn: "#pass"
       facebookLoginBtn: "#loginbutton"
       
    registerpage:
       yourEmailIn: "input[name=email]"
       firstNameIn: "input[name=fname]"
       lastNameIn: "input[name=lname]"
       passwordNewIn: "input[name=new-password]"
       passwordConfirmIn: "input[name=new-password-confirm]"
       telephoneIn: "input[name=phone]"
       registerConfirmationTxt: "page-account-register > main > account-register > div > p > strong" # email of a jast registered user
    thankyoupage:
       txtContent: "app-root"
    explorepage:
       loginBtn: "a[routerlink='/user/login']"
       userNameTxt: "a[routerlink='/profile']"
       profileBtn: ".button.mat-icon-button"
       menuAdmin: "a.mat-list-link[href='https://admin.dev.corite.com/']"
       menuMyCampaign: "a.mat-list-link[href='/my-campaigns']"
       menuLogoutBtn: "button.mat-list-link"
       startCampaignTab: "a.mat-tab-link:nth-child(2)"
       firstCampaignInList: "campaign-explore-teaser"
    explorecappaignpage:
       buyCoritesBtn: "a[routerlink=invest]"
    startcampaignpage:
       campaignImage: "campaign-group-own-image input"
       campaignSong: "campaign-group-own-song input"
       campaignName: "campaign-group-own-basics input[name='campaign[name]']"
       campaignArtist: "campaign-group-own-basics input[name='campaign[artist]']"
       campaignGenre: "campaign-group-own-genre input"
       campaignGenreSelect: "div.mat-autocomplete-panel > mat-option:nth-of-type(1)"
       campaignValue: "mat-slider"
       textArea: "textarea"
       iagree: ".mat-checkbox-inner-container"
       #campaignPublish: ".mat-flat-button.mat-primary"
    moderationpage:   
       acceptedModeration: "#campaign_moderationStatus_2"
       saveChangesModeration: "button.action-save"
    investpage:
       campaignStatus: "campaign-status"
       slider: "mat-slider"
       #nextBtn: ".mat-flat-button.mat-primary"
       buyCoritesBtn: "a[routerlink=invest]"
       #accentBtn: ".mat-flat-button.mat-accent"
       #pledgeBtn: ".mat-flat-button.mat-primary"
       thankyou: "campaign-invest-thankyou"
    adminpage:
       searchQuery: "input[name=query]" 
       searchBtn: "button[type=submit].btn"
       dropdownMenuBtn: "td div button.btn.dropdown-toggle"
       deleteUserBtn: "a.action-delete"
       confirmDeleteUserBtn: "#modal-delete-button"
       searshResultsNumber: "h1.title > strong"
       detectedItem: "tr[data-id]"
    releaseinfopage:
       songName: "input[name='campaign[release][songName]']"
       cover: "app-file-upload div.item input"
       label: "input[name='campaign[release][label]']"
       company: "input[name='campaign[release][company]']"
       isrc: "input[name='campaign[release][ISRC]']"
       artists: "input[name='campaign[release][contribArtists]']"       
       producers: "input[name='campaign[release][contribProducers]']"
       composers: "input[name='campaign[release][contribComposers]']"
       mixers: "input[name='campaign[release][contribMixers]']"
       publishers: "input[name='campaign[release][contribPublishers]']"
       countries: "div.mat-select-value"
       country: "#mat-option-83"
       date: "input[min]"
       #releaseBtn: ".mat-flat-button.mat-primary"

flowsss:
    loginlogout:

    registerwithemail:
    
    releaseinformation:
#0 Page after cliking on link in campaign declining email message. Campaign Id: 295
#      - csss: "page-campaign-own-edit"
#        hash: "-181239646" #"593831657"
        
    releasecampaign:
      - csss: "page-campaign-own-edit"
        hash: "-181239646"
    
    startcampaign:
#0 
      - csss: "explore-teaser" # css selector to check hash of its innerhtml
        hash: "-14973616" # hashcode of the element's innerHTML
#1
      - csss: "page-explore-view"
        hash: "1"
#2
      - csss: "page-explore-view"
        hash: "2"
        
    incorrectcard:
    
patterns:
#  id: pattern
     1: Eagle

logger:
    debug: true
    action: true
    info: true
    passed: true
    warning: true
    failed: true

runtests: 
#   - loginlogout
#   - registerwithemail
#   - startcampaign
#   - releaseinformation
   - releasecampaign
#    - incorrectcard